FROM python:3.11-slim

WORKDIR /app

# Копируем файлы приложения
COPY server.py .
COPY database.py .
COPY init_db.py .
COPY templates/ templates/

# Создаем директорию для БД (будет монтироваться как volume)
RUN mkdir -p /app/data

# Запускаем сервер
CMD ["python3", "server.py"]

