FROM nginx:alpine

# Копируем конфигурацию nginx
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Копируем только статические файлы (CSS)
COPY static/style.css /usr/share/nginx/html/static/

# Создаем директорию для логов
RUN mkdir -p /var/log/nginx

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]

